# Generated by Django 4.0.1 on 2022-02-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chemical', '0005_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantBiotechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantStore', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.store')),
            ],
        ),
        migrations.CreateModel(
            name='MicrobialBiotechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microbialStore', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.store')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalBiotechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalStore', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.store')),
            ],
        ),
    ]
