# Generated by Django 4.0.1 on 2022-02-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0009_request_checked'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinate', models.CharField(max_length=100)),
                ('shelf', models.CharField(max_length=100)),
                ('available', models.IntegerField(default=0)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='MicrobialStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinate', models.CharField(max_length=100)),
                ('shelf', models.CharField(max_length=100)),
                ('available', models.IntegerField(default=0)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='PlantStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinate', models.CharField(max_length=100)),
                ('shelf', models.CharField(max_length=100)),
                ('available', models.IntegerField(default=0)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.chemical')),
            ],
        ),
        migrations.RemoveField(
            model_name='microbialbiotechnology',
            name='microbialStore',
        ),
        migrations.RemoveField(
            model_name='plantbiotechnology',
            name='plantStore',
        ),
        migrations.DeleteModel(
            name='AnimalBiotechnology',
        ),
        migrations.DeleteModel(
            name='MicrobialBiotechnology',
        ),
        migrations.DeleteModel(
            name='PlantBiotechnology',
        ),
    ]
