# Generated by Django 4.0.1 on 2022-02-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_animalstore_microbialstore_plantstore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalstore',
            name='expireDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='animalstore',
            name='recievedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialstore',
            name='expireDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='microbialstore',
            name='recievedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plantstore',
            name='expireDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='plantstore',
            name='recievedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
