# Generated by Django 4.0.1 on 2022-03-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_animalstore_expiredate_animalstore_recieveddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalstore',
            name='productionDate',
            field=models.DateField(null=True),
        ),
    ]
