# Generated by Django 4.0.1 on 2022-03-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0012_alter_request_options'),
        ('department', '0004_animalstore_productiondate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDesposedChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinate', models.CharField(max_length=100)),
                ('shelf', models.CharField(max_length=100)),
                ('available', models.IntegerField(default=0)),
                ('recievedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('expireDate', models.DateField(null=True)),
                ('desposed', models.BooleanField(default=False)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='MicrobialDesposedChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinate', models.CharField(max_length=100)),
                ('shelf', models.CharField(max_length=100)),
                ('available', models.IntegerField(default=0)),
                ('recievedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('expireDate', models.DateField(null=True)),
                ('desposed', models.BooleanField(default=False)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalDesposedChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinate', models.CharField(max_length=100)),
                ('shelf', models.CharField(max_length=100)),
                ('available', models.IntegerField(default=0)),
                ('recievedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('expireDate', models.DateField(null=True)),
                ('desposed', models.BooleanField(default=False)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.chemical')),
            ],
        ),
    ]
