# Generated by Django 4.0.1 on 2022-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_animaldesposedchemical_desposeddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaldesposedchemical',
            name='fridge',
            field=models.CharField(choices=[('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='animalstore',
            name='fridge',
            field=models.CharField(choices=[('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='microbialdesposedchemical',
            name='fridge',
            field=models.CharField(choices=[('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='microbialstore',
            name='fridge',
            field=models.CharField(choices=[('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='plantdesposedchemical',
            name='fridge',
            field=models.CharField(choices=[('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='plantstore',
            name='fridge',
            field=models.CharField(choices=[('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='animalstore',
            name='cabinate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animalstore',
            name='shelf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microbialstore',
            name='cabinate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microbialstore',
            name='shelf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantstore',
            name='cabinate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantstore',
            name='shelf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
