# Generated by Django 4.0.1 on 2022-04-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_animaldesposedchemical_fridge_animalstore_fridge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaldesposedchemical',
            old_name='fridge',
            new_name='temprature',
        ),
        migrations.RenameField(
            model_name='animalstore',
            old_name='fridge',
            new_name='temprature',
        ),
        migrations.RenameField(
            model_name='microbialdesposedchemical',
            old_name='fridge',
            new_name='temprature',
        ),
        migrations.RenameField(
            model_name='microbialstore',
            old_name='fridge',
            new_name='temprature',
        ),
        migrations.RenameField(
            model_name='plantdesposedchemical',
            old_name='fridge',
            new_name='temprature',
        ),
        migrations.RenameField(
            model_name='plantstore',
            old_name='fridge',
            new_name='temprature',
        ),
    ]
