# Generated by Django 4.0.1 on 2022-04-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_rename_fridge_animaldesposedchemical_temprature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldesposedchemical',
            name='temprature',
            field=models.CharField(choices=[('-', '-'), ('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='animalstore',
            name='temprature',
            field=models.CharField(choices=[('-', '-'), ('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='microbialdesposedchemical',
            name='temprature',
            field=models.CharField(choices=[('-', '-'), ('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='microbialstore',
            name='cabinate',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='microbialstore',
            name='shelf',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='microbialstore',
            name='temprature',
            field=models.CharField(choices=[('-', '-'), ('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantdesposedchemical',
            name='temprature',
            field=models.CharField(choices=[('-', '-'), ('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantstore',
            name='temprature',
            field=models.CharField(choices=[('-', '-'), ('+4', '+4'), ('-20', '-20'), ('-80', '-80')], default='-', max_length=100),
        ),
    ]
