# Generated by Django 4.0.1 on 2022-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
