# Generated by Django 4.0.1 on 2022-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0002_alter_request_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchemical',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
