# Generated by Django 4.0.1 on 2022-02-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0003_requestchemical_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
