# Generated by Django 4.0.1 on 2022-02-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0004_request_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinate', models.CharField(max_length=100)),
                ('shelf', models.CharField(max_length=100)),
                ('available', models.IntegerField(default=0)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chemical.chemical')),
            ],
        ),
    ]
