# Generated by Django 4.0.1 on 2022-02-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0005_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='expireDate',
        ),
    ]
