# Generated by Django 4.0.1 on 2022-02-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0006_remove_chemical_expiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
