# Generated by Django 4.0.1 on 2022-02-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0007_request_deny_alter_chemical_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchemical',
            name='issuedquantity',
            field=models.IntegerField(default=0),
        ),
    ]
