# Generated by Django 4.0.1 on 2022-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0010_request_pin_delete_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deptRequest',
            field=models.BooleanField(default=False),
        ),
    ]
