# Generated by Django 4.0.1 on 2022-02-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0011_request_deptrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-ordered_date', '-received']},
        ),
    ]
