# Generated by Django 4.0.1 on 2022-04-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0012_alter_request_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
