# Generated by Django 4.0.1 on 2022-02-05 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(choices=[('Microbial Biotechnlogy', 'Microbial Biotechnlogy'), ('Animal Biotechnology', 'Animal Biotechnology'), ('Plant Biotechnology', 'Plant Biotechnology')], default='-', max_length=100)),
                ('researcher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
