# Generated by Django 4.0.1 on 2022-02-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_director_department_custodian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='director',
        ),
    ]
