# Generated by Django 4.0.1 on 2022-02-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_custodian_phone_alter_department_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
