# Generated by Django 4.0.1 on 2022-02-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('Microbial Biotechnology', 'Microbial Biotechnology'), ('Animal Biotechnology', 'Animal Biotechnology'), ('Plant Biotechnology', 'Plant Biotechnology')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='department',
            field=models.CharField(choices=[('Microbial Biotechnology', 'Microbial Biotechnology'), ('Animal Biotechnology', 'Animal Biotechnology'), ('Plant Biotechnology', 'Plant Biotechnology')], default='-', max_length=100),
        ),
    ]
