# Generated by Django 4.0.1 on 2022-03-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_department_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
